List image = [
  "assets/img/gg.jpg",
  "assets/img/bb.jpg",
  "assets/img/cc.png",
  "assets/img/dd.jpg",
  "assets/img/ee.png",
  "assets/img/ff.png",
  "assets/img/gg.jpg",
  "assets/img/bb.jpg",
  "assets/img/cc.png",
  "assets/img/dd.jpg",
  "assets/img/ee.png",
  "assets/img/ff.png",
];
List rname = [
  "Raghu Franky",
  "LittiWale",
  "Jail chai Bar",
  "Amdavadi DalVada Centre",
  "Gupta Chat Centre",
  "The Mothers Kitchen",
  "Raghu Franky",
  "LittiWale",
  "Jail chai Bar",
  "Amdavadi DalVada Centre",
  "Gupta Chat Centre",
  "The Mothers Kitchen",
];
List category = [
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
  "Fast Food Corners",
];
List dtime = [
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
  "Delivery in 35 mins",
];
List off = [
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
  "Upto 5% off",
];
